# here we generate subsets with and without read threshold to check
# the number of OTUs present per subset

# Set the working dir with mothur files (with singletons) in it
setwd("/data/projects/glyphosate/reads/mothur_processed/")
load("mothur_glyph_002.RData")

.cran_packages <- c("ggplot2", 
					"gridExtra")
.bioc_packages <- c("dada2", 
					"phyloseq", 
					"DECIPHER", 
					"phangorn")

# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)


# this is the subsetting function
get_sample_subsets <- function(ps, nucleic_acid, habitat, days, threshold){
	sample_subset <- sample_data(ps)[ which(sample_data(ps)$nucleic_acid == nucleic_acid & 
											sample_data(ps)$habitat == habitat & 
											sample_data(ps)$days > days),]
	phy_subset <- merge_phyloseq(tax_table(ps), 
								 otu_table(ps),
								 #phy_tree(ps),
								 refseq(ps),
								 sample_subset)
	phy_subset2 <- filter_taxa(phy_subset, function (x) {sum(x > threshold) >= 1 }, prune = TRUE)
	return(phy_subset2)
}

# these are the arguments for the subsetting function
ps <- mothur_ps2
acids <- c("dna", "cdna")
habitats <- c("water", "biofilm")
threshold <- 1
after_day <- 43

# these are additional phyloseq derived objects
mothur_ps2 <- subset_samples(mothur_ps2, days > 43, prune = TRUE)
mothur_ps2_ra <- transform_sample_counts(mothur_ps2, function(x){(x / sum(x)) * 100})
mothur_ps3 <- filter_taxa(mothur_ps2, function (x) {sum(x > 1) >= 1}, prune = TRUE)
mothur_ps3_ra <- transform_sample_counts(mothur_ps3, function(x){(x / sum(x)) * 100})

# to increase melting speed, check http://chuckpr.github.io/blog/melt.html
mothur_ra_melt <- psmelt(mothur_ps3_ra)

# in this list we store the different sample subsets, generated by the for loops
sample_subset_list <- list() 
if(length(sample_subset_list) == 0) {
	for (each_day in after_day){
		for (acid in acids) {
			for (habitat in habitats) {
				print(paste0("nucleic_acid is ", acid, " and habitat is ", 
							 habitat, " and first day is ", each_day))
				tmp <-	get_sample_subsets(ps = ps, 
									   nucleic_acid = acid, 
									   habitat = habitat, 
									   days = each_day, 
									   threshold = threshold)
				sample_data(tmp)$days <- as.factor(sample_data(tmp)$days)					   
				sample_data(tmp)$new_day <- as.factor(sample_data(tmp)$new_day)
				sample_subset_list[[paste(habitat, 
										  "after day", 
										  each_day, 
										  acid, 
										  "min reads per OTU", 
										  threshold, 
										  sep = " ")]] <- tmp
			}
		}
	}
print(sample_subset_list)
} else {
	print("list is not empty, abort to prevend appending...")
}

# the distribution of sequence length can be addressed using
table(width(refseq(sample_subset_list[[1]])))

# library sizes are returned using
sample_sums(mothur_ps2)

# how many OTUs belong to which genus?
genus_distribution <- aggregate(Abundance ~ OTU + genus, 
								data = mothur_ra_melt, 
								max)
								
genus_distribution2 <- aggregate(Abundance ~ OTU + habitat + genus + nucleic_acid, 
								data = mothur_ra_melt, 
								max)
							
genus_distribution3 <- aggregate(OTU ~ genus, 
								data = genus_distribution, 
								length)
								
otu_per_genus <- as.data.frame(table(genus_distribution$genus))
otu_per_genus[order(otu_per_genus$Freq),]
# how many genera?
length(table(genus_distribution$genus))

